import logging

from openupgradelib import openupgrade

_logger = logging.getLogger(__name__)


@openupgrade.migrate()
def migrate(env, version):
    cr = env.cr

    cr.execute(
        """
        SELECT id, name, state, latest_version
          FROM ir_module_module
         WHERE name IN ('payment_redsys', 'payment_redsys_oca')
         ORDER BY name
        """
    )
    _logger.info(
        "Servitrapo Redsys migration - modules before migration: %s",
        cr.fetchall(),
    )

    # ---------------------------------------------------------------------
    # 1. Locate the historical OCA Redsys provider.
    # ---------------------------------------------------------------------
    cr.execute(
        """
        SELECT id,
               redsys_merchant_code,
               redsys_terminal,
               redsys_secret_key
          FROM payment_provider
         WHERE code = 'redsys'
         ORDER BY id
         LIMIT 1
        """
    )
    provider_row = cr.fetchone()

    if not provider_row:
        _logger.info(
            "No historical Redsys provider found; "
            "only module metadata migration will be performed"
        )
        historical_provider_id = None
        merchant_code = None
        merchant_terminal = None
        secret_key = None
    else:
        (
            historical_provider_id,
            merchant_code,
            merchant_terminal,
            secret_key,
        ) = provider_row

        _logger.info(
            "Historical Redsys provider found: id=%s, "
            "merchant_present=%s, terminal_present=%s, secret_present=%s",
            historical_provider_id,
            bool(merchant_code),
            bool(merchant_terminal),
            bool(secret_key),
        )

        # Odoo 19 replaces redsys_terminal with
        # redsys_merchant_terminal.
        cr.execute(
            """
            ALTER TABLE payment_provider
            ADD COLUMN IF NOT EXISTS redsys_merchant_terminal varchar
            """
        )

        cr.execute(
            """
            UPDATE payment_provider
               SET redsys_merchant_terminal = %s
             WHERE id = %s
            """,
            (merchant_terminal, historical_provider_id),
        )

    # ---------------------------------------------------------------------
    # 2. Locate the temporary native Odoo 19 provider generated by the
    #    Upgrade Service.
    # ---------------------------------------------------------------------
    cr.execute(
        """
        SELECT res_id
          FROM ir_model_data
         WHERE module = 'payment'
           AND name = 'payment_provider_redsys'
           AND model = 'payment.provider'
         LIMIT 1
        """
    )
    native_xmlid_row = cr.fetchone()
    native_placeholder_id = native_xmlid_row[0] if native_xmlid_row else None

    if (
        historical_provider_id
        and native_placeholder_id
        and native_placeholder_id != historical_provider_id
    ):
        # Do not delete a provider carrying business/history data.
        # payment_method_payment_provider_rel is excluded because those
        # relations are intentionally transferred below.
        cr.execute(
            """
            SELECT
                (SELECT COUNT(*)
                   FROM payment_transaction
                  WHERE provider_id = %s)
              + (SELECT COUNT(*)
                   FROM payment_token
                  WHERE provider_id = %s)
              + (SELECT COUNT(*)
                   FROM account_payment_method_line
                  WHERE payment_provider_id = %s)
              + (SELECT COUNT(*)
                   FROM payment_country_rel
                  WHERE payment_id = %s)
              + (SELECT COUNT(*)
                   FROM payment_currency_rel
                  WHERE payment_provider_id = %s)
              + (SELECT COUNT(*)
                   FROM payment_provider_pos_payment_method_rel
                  WHERE payment_provider_id = %s)
            """,
            (
                native_placeholder_id,
                native_placeholder_id,
                native_placeholder_id,
                native_placeholder_id,
                native_placeholder_id,
                native_placeholder_id,
            ),
        )
        blocking_refs = cr.fetchone()[0]

        if blocking_refs:
            raise RuntimeError(
                "Native Redsys placeholder still has protected references; "
                "migration aborted"
            )

        # Preserve native Odoo payment-method relations such as
        # card and bizum.
        cr.execute(
            """
            INSERT INTO payment_method_payment_provider_rel
                (payment_provider_id, payment_method_id)
            SELECT %s, payment_method_id
              FROM payment_method_payment_provider_rel
             WHERE payment_provider_id = %s
            ON CONFLICT DO NOTHING
            """,
            (historical_provider_id, native_placeholder_id),
        )

        # The canonical Odoo XML ID must reference the historical provider.
        cr.execute(
            """
            UPDATE ir_model_data
               SET res_id = %s
             WHERE module = 'payment'
               AND name = 'payment_provider_redsys'
               AND model = 'payment.provider'
            """,
            (historical_provider_id,),
        )

        cr.execute(
            """
            DELETE FROM payment_method_payment_provider_rel
             WHERE payment_provider_id = %s
            """,
            (native_placeholder_id,),
        )

        cr.execute(
            """
            DELETE FROM payment_provider
             WHERE id = %s
            """,
            (native_placeholder_id,),
        )

        _logger.info(
            "Native Redsys placeholder %s removed after transferring "
            "its payment-method relations to provider %s",
            native_placeholder_id,
            historical_provider_id,
        )

    # ---------------------------------------------------------------------
    # 3. Remove OCA technical views BEFORE the module-name merge.
    #
    #    They reference Odoo 18-only fields such as:
    #      redsys_merchant_name
    #      redsys_terminal
    #      redsys_currency
    #      redsys_transaction_type
    #      redsys_merchant_lang
    #      redsys_pay_method
    #
    #    These views must never become payment_redsys.* records in Odoo 19.
    # ---------------------------------------------------------------------
    cr.execute(
        """
        SELECT res_id
          FROM ir_model_data
         WHERE module = 'payment_redsys_oca'
           AND model = 'ir.ui.view'
        """
    )
    legacy_view_ids = [row[0] for row in cr.fetchall()]

    if legacy_view_ids:
        # Avoid leaving the historical provider pointing to the obsolete
        # OCA redirect/QWeb view.
        if historical_provider_id:
            cr.execute(
                """
                UPDATE payment_provider
                   SET redirect_form_view_id = NULL
                 WHERE id = %s
                   AND redirect_form_view_id = ANY(%s)
                """,
                (historical_provider_id, legacy_view_ids),
            )

        cr.execute(
            """
            DELETE FROM ir_ui_view
             WHERE id = ANY(%s)
            """,
            (legacy_view_ids,),
        )

        _logger.info(
            "Removed %s legacy OCA Redsys views before native module load",
            len(legacy_view_ids),
        )

    # ---------------------------------------------------------------------
    # 4. Remove all old payment_redsys_oca XML-ID ownership.
    #
    #    IMPORTANT:
    #    This removes ir_model_data aliases only. It does NOT delete:
    #      - provider 16
    #      - payment transactions
    #      - payment methods
    #      - accounting payment methods
    #
    #    It prevents OpenUpgrade from moving old OCA field/view metadata
    #    into the native payment_redsys namespace.
    # ---------------------------------------------------------------------
    cr.execute(
        """
        SELECT COUNT(*)
          FROM ir_model_data
         WHERE module = 'payment_redsys_oca'
        """
    )
    legacy_xmlid_count = cr.fetchone()[0]

    cr.execute(
        """
        DELETE FROM ir_model_data
         WHERE module = 'payment_redsys_oca'
        """
    )

    _logger.info(
        "Removed %s legacy payment_redsys_oca XML IDs before module merge",
        legacy_xmlid_count,
    )

    # ---------------------------------------------------------------------
    # 5. Merge the obsolete OCA module state into native Odoo payment_redsys.
    # ---------------------------------------------------------------------
    cr.execute(
        """
        SELECT 1
          FROM ir_module_module
         WHERE name = 'payment_redsys_oca'
        """
    )

    if cr.fetchone():
        openupgrade.update_module_names(
            cr,
            [('payment_redsys_oca', 'payment_redsys')],
            merge_modules=True,
        )

    # ---------------------------------------------------------------------
    # 6. Associate historical provider with native module and restore the
    #    critical Redsys credentials.
    #
    #    Values are never logged.
    # ---------------------------------------------------------------------
    if historical_provider_id:
        cr.execute(
            """
            UPDATE payment_provider
               SET module_id = (
                       SELECT id
                         FROM ir_module_module
                        WHERE name = 'payment_redsys'
                        LIMIT 1
                   ),
                   redsys_merchant_code = %s,
                   redsys_merchant_terminal = %s,
                   redsys_secret_key = %s
             WHERE id = %s
            """,
            (
                merchant_code,
                merchant_terminal,
                secret_key,
                historical_provider_id,
            ),
        )

        cr.execute(
            """
            SELECT
                COUNT(*),
                COUNT(*) FILTER (WHERE state = 'done'),
                COUNT(*) FILTER (WHERE state = 'draft')
              FROM payment_transaction
             WHERE provider_id = %s
            """,
            (historical_provider_id,),
        )
        tx_total, tx_done, tx_draft = cr.fetchone()

        _logger.info(
            "Historical Redsys provider %s preserved with "
            "%s transactions (%s done, %s draft)",
            historical_provider_id,
            tx_total,
            tx_done,
            tx_draft,
        )

    cr.execute(
        """
        SELECT id, name, state, latest_version
          FROM ir_module_module
         WHERE name IN ('payment_redsys', 'payment_redsys_oca')
         ORDER BY name
        """
    )

    _logger.info(
        "Servitrapo Redsys migration - modules after migration: %s",
        cr.fetchall(),
    )
